USE [master]
GO

CREATE DATABASE [RentDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RentDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RentDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RentDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RentDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [RentDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RentDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RentDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RentDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RentDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RentDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RentDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [RentDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RentDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RentDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RentDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RentDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RentDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RentDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RentDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RentDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RentDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RentDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RentDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RentDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RentDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RentDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RentDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RentDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RentDB] SET RECOVERY FULL 
GO
ALTER DATABASE [RentDB] SET  MULTI_USER 
GO
ALTER DATABASE [RentDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RentDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RentDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RentDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RentDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'RentDB', N'ON'
GO
ALTER DATABASE [RentDB] SET QUERY_STORE = OFF
GO
USE [RentDB]
GO
/****** Object:  Table [dbo].[tbl_Customers]    Script Date: 22.02.2019 20:48:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Customers](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[CustomerName] [nvarchar](50) NOT NULL,
	[CustomerSurname] [nvarchar](50) NOT NULL,
	[CustomerPasskey] [nvarchar](50) NOT NULL,
	[CustomerTC] [int] NOT NULL
 CONSTRAINT [PK_tbl_Customers] PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tbl_Transactions]    Script Date: 22.02.2019 20:48:17 ******/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Arac](
	[AracID] [int] IDENTITY(1,1) NOT NULL,
	[AitOlduguSirket] [int] NOT NULL,
	[Marka] [varchar] (50) NULL,
	[Model] [varchar] (50) NOT NULL,
	[Yýl] [int] NOT NULL,
	[Uygunluk] [bit] NOT NULL,
	[GünlükFiyat] [money] NOT NULL,
 CONSTRAINT [PK_tbl_Arac] PRIMARY KEY CLUSTERED 
(
	[AracID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tbl_Transactions]    Script Date: 22.02.2019 20:48:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Kiralama](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KiralayanKisi] [int] NOT NULL,
	[KiralananArac] [int] NOT NULL,
	[KiralamaTarih] [datetime] NOT NULL
 CONSTRAINT [PK_tbl_Kiralama] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tbl_Transactions]    Script Date: 22.02.2019 20:48:17 ******/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Sirket](
	[SirketID] [int] IDENTITY(1,1) NOT NULL,
	[SirketAdi] [varchar] (50) NOT NULL,
	[SirketAdres] [varchar] (50) NOT NULL,
	[AracSayisi] [int] NOT NULL,
	[SirketPuani] [decimal] NOT NULL,
 CONSTRAINT [PK_tbl_Sirket] PRIMARY KEY CLUSTERED 
(
	[SirketID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tbl_Transactions]    Script Date: 22.02.2019 20:48:17 ******/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Teslim](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TeslimTarihi] [datetime] NOT NULL,
	[Odeme] [money] NOT NULL,
	[TeslimEdenKisi] [int] NOT NULL,
	[TeslimEdilenArac] [int] NOT NULL,
 CONSTRAINT [PK_tbl_Teslim] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tbl_Transactions]    Script Date: 22.02.2019 20:48:17 ******/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_UserLogin](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar] (50) NOT NULL,
	[Password] [varchar] (50) NULL,
	[isActive] [bit] NOT NULL,
 CONSTRAINT [PK_tbl_UserLogin] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_ManagerLogin](
	[ManagerID] [int] IDENTITY(1,1) NOT NULL,
	[ManagerName] [varchar] (50) NOT NULL,
	[Password] [varchar] (50) NULL,
	[isActive] [bit] NOT NULL,
 CONSTRAINT [PK_tbl_ManagerLogin] PRIMARY KEY CLUSTERED 
(
	[ManagerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
GO
ALTER TABLE [dbo].[tbl_Kiralama]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Kiralama_tbl_Customers1] FOREIGN KEY([KiralayanKisi])
REFERENCES [dbo].[tbl_Customers] ([CustomerID])
GO
ALTER TABLE [dbo].[tbl_Kiralama] CHECK CONSTRAINT [FK_tbl_Kiralama_tbl_Customers1]
GO
GO
ALTER TABLE [dbo].[tbl_Kiralama]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Kiralama_tbl_Arac1] FOREIGN KEY([KiralananArac])
REFERENCES [dbo].[tbl_Arac] ([AracID])
GO
ALTER TABLE [dbo].[tbl_Kiralama] CHECK CONSTRAINT [FK_tbl_Kiralama_tbl_Arac1]
GO
GO
ALTER TABLE [dbo].[tbl_Teslim]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Teslim_tbl_Customers1] FOREIGN KEY([TeslimEdenKisi])
REFERENCES [dbo].[tbl_Customers] ([CustomerID])
GO
ALTER TABLE [dbo].[tbl_Teslim] CHECK CONSTRAINT [FK_tbl_Teslim_tbl_Customers1]
GO
GO
ALTER TABLE [dbo].[tbl_Teslim]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Teslim_tbl_Arac1] FOREIGN KEY([TeslimEdilenArac])
REFERENCES [dbo].[tbl_Arac] ([AracID])
GO
ALTER TABLE [dbo].[tbl_Teslim] CHECK CONSTRAINT [FK_tbl_Teslim_tbl_Arac1]
GO
GO
ALTER TABLE [dbo].[tbl_Arac]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Arac_tbl_Sirket1] FOREIGN KEY([AitOlduguSirket])
REFERENCES [dbo].[tbl_Sirket] ([SirketID])
GO
ALTER TABLE [dbo].[tbl_Arac] CHECK CONSTRAINT [FK_tbl_Arac_tbl_Sirket1]
GO
GO
USE [master]
GO
ALTER DATABASE [RentDB] SET  READ_WRITE 
GO